services:
  - type: web
    name: anime-arcadia-api
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend.vercel.app
